export {
  LEGACY_MOCK_SUMMARY_MEETING_ID,
  MOCK_STANDUP_DAYS,
  MOCK_STANDUP_MEETING_IDS,
  MOCK_STANDUP_PARTICIPANTS,
  MOCK_STANDUP_STORY_INTRO,
  MOCK_SUMMARY_MEETING_ID,
  buildMockStandupSearchSuggestions,
  buildMockSummaryMeetingSearchSuggestions,
  buildStandupStorySearchSuggestions,
  getMockStandupDay,
  getMockStandupMeetingDisplay,
  getMockStandupMeetings,
  getMockSummaryMeetingDisplay,
  isMockStandupMeeting,
  isMockSummaryMeeting,
  prependMockStandupMeetings,
  prependMockSummaryMeeting,
  type MockStandupDay,
  type MockStandupMeetingDisplay,
} from "@/lib/meetings/mock-standup-story";
